services:
  db:
    container_name: "postgres"
    image: postgres
    restart: always
    environment:
      - POSTGRES_NAME=${USER_NAME_DB}
      - POSTGRES_PASSWORD=${USER_PASS_DB}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=./data/db
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - backend
  fastapi:
    container_name: "fastapi"
    build:
      dockerfile: src/fast_api/Dockerfile
    command: uvicorn src.loader:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/code
    networks:
      - backend
  bot:
    container_name: "bot"
    build:
      dockerfile: src/bot/Dockerfile
    command: python main.py
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
    networks:
      - backend
    links:
      - fastapi

#  cron_run:
#    container_name: "cron_run"
#    build: ./crontab
#    command: cron -n
#    depends_on:
#      - bot
#    networks:
#      - backend

networks:
  backend:
    driver: bridge

volumes:
  db:
    driver: local