[tool.poetry]
name = "bottracking"
version = "0.1.0"
description = "A chatbot that gives users the ability to effectively manage their habits via Telegram."
authors = ["Evgenator"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
